### PR TITLE
Text overwrite and automatic word wrap in receive pane

### LINKED ISSUE #200: Receive Pane lack of scroll on word wrap
The Receive Pane now seems to fail to scroll when word wrap happens.  [See the video](https://drive.google.com/file/d/0B0tev9Y3WaL4d19BaGdYTDdZem8/view?usp=sharing) for a demo.

### LINKED ISSUE #201: Debug Terminal: Need to perform in overwrite mode always
The Debug Terminal's Receive Pane needs to treat all visible changes as an _overwrite_ mode rather than an _insert_ mode as specified by the [Debug Terminal document](https://docs.google.com/document/d/1u0L0WTVU-jfvN4H56efHdBhNYTbObEX72Bn7Fc2RxwE/edit?usp=sharing):
- All characters emitted to the display do so in an overwrite fashion; no existing text is moved by any operation

Currently, the Receive Pane seems to act like it's in _Insert_ mode as demonstrated by this code:

```
'{$STAMP BS2}
'{$PBASIC 2.5}

  PAUSE 1000

  FOR W0 = 1 TO 10
    DEBUG "Text: ", DEC W0, CR
    PAUSE 100
  NEXT

  DEBUG HOME
  DEBUG "Home'd Text"
```

which produces this display:
image

instead of this display (from BSE):
image

### LINKED ISSUE #203: Debug Terminal: Make each line a max 256 characters wide
Enhance Debug Terminal's Receive Pane to a maximum width of 256 characters (column positions 0..255), as specified in the [Debug Terminal document](https://docs.google.com/document/d/1u0L0WTVU-jfvN4H56efHdBhNYTbObEX72Bn7Fc2RxwE/edit?usp=sharing)
- Each line of the display is designed to be a maximum of 256 characters wide; column 0 to 255
  ...

### PR DESCRIPTION
**Pull request by 2fast2fourier**
#### What's this PR do?

This PR addresses issues raised in #201 and #203. The receive pane now automatically overwrites text when the cursor is not at the end and automatically wraps lines after 256 characters.
#### What are the important parts of the code?

The important change is to `addText` in the terminal store, the updated console logic handles line wrap and overwrite.
#### How should this be tested by the reviewer?

Run the code mentioned in #201 and verify other text functionality still functions as expected with this older test program: https://gist.github.com/2fast2fourier/dc7748f98a676094b6f8
#### Is any other information necessary to understand this?

This also disables automatic line wrap in the terminal viewport, as this was causing early line wrap in some cases.
#### What are the relevant tickets? (Please add `closes`, `refs`, etc)

Closes #200
Closes #201 
Closes #203

### CODE REVIEW

File: src/lib/terminal.js [hunk 1]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
-      lines[pointerLine] = start + data + end;
-    }else if(pointerColumn > line.length){
-      lines[pointerLine] = _.padRight(line, pointerColumn) + data;
-    }else{
-      lines[pointerLine] = line + data;
+    const { lines, lineWrap, pointerLine, pointerColumn, trimCount, maxLines } = this.state;
+
+    var newPointerColumn = pointerColumn;
+    var newPointerLine = pointerLine;
+    var newText = data;
```
Comment (phated) [inline src/lib/terminal.js]: just make the argument `newText`

File: src/lib/terminal.js [hunk 2]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
-      const start = line.slice(0, pointerColumn);
-      const end = line.slice(pointerColumn);
-      lines[pointerLine] = start + data + end;
-    }else if(pointerColumn > line.length){
-      lines[pointerLine] = _.padRight(line, pointerColumn) + data;
-    }else{
-      lines[pointerLine] = line + data;
+    const { lines, lineWrap, pointerLine, pointerColumn, trimCount, maxLines } = this.state;
+
+    var newPointerColumn = pointerColumn;
```
Comment (phated) [inline src/lib/terminal.js]: use `let` instead of `var` throughout

File: src/lib/terminal.js [hunk 3]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
+    var newPointerLine = pointerLine;
```
Comment (phated) [inline src/lib/terminal.js]: why are you defining this as `newPointerLine`? It seems like you can just use `pointerLine` since it only gets incremented if the line wraps

File: src/lib/terminal.js (hunk 2 above)
Comment (phated) [inline src/lib/terminal.js]: why are you defining this as `newPointerColumn`?  It seems like it would be fine as just `pointerColumn`

File: src/lib/terminal.js [hunk 4]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
+    var newText = data;
+
+    while(newText.length > 0){
+      var oldLine = lines[newPointerLine] || '';
+      var initial = _.padRight(oldLine.slice(0, newPointerColumn), newPointerColumn);
```
Comment (phated) [inline src/lib/terminal.js]: why is this being padded?

File: src/lib/terminal.js [hunk 5]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
+
+      var newData = newText.slice(0, lineWrap - initial.length);
```
Comment (phated) [inline src/lib/terminal.js]: Is there a chance to end in a negative?  If so, we should wrap them in Math.max(..., 0)

File: src/lib/terminal.js [hunk 6]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
+
+      var remainder = oldLine.slice(newData.length + initial.length);
+
+      var leftOver = newText.slice(lineWrap - initial.length);
```
Comment (phated) [inline src/lib/terminal.js]: Is there a chance to end in a negative?  If so, we should wrap them in Math.max(..., 0)

File: src/lib/terminal.js [hunk 7]
```diff
@@ -168,25 +168,41 @@ class Terminal {
...
+        newPointerColumn = initial.length + newData.length;
+      }
     }
 
     if(lines.length > maxLines){
       const newLines = lines.slice(trimCount);
       this.state.lines = newLines;
-      this.state.pointerLine = Math.max(0, pointerLine - trimCount);
-      this.state.pointerColumn = pointerColumn + data.length;
+      this.state.pointerLine = Math.max(0, newPointerLine - trimCount);
```
Comment (phated) [inline src/lib/terminal.js]: Is there a chance to end in a negative?  If so, we should wrap them in Math.max(..., 0)
